### ISSUE TITLE
e2e tests fail with "NCCL operations have failed or timed out"

### ISSUE THREAD

**Issue by ktdreyer** [instructlab/instructlab#3321]
**Describe the bug**
Our end-to-end tests fail on `main` with errors about `NCCL operations have failed or timed out`

**To Reproduce**
1. Run the end-to-end tests, for example `E2E (NVIDIA L40S x4)`
2. The job will fail about 3 hours in.

The logs look like this ([example](https://github.com/instructlab/instructlab/actions/runs/14711738459/job/41285794237)):
```
[rank2]:[E428 18:32:18.066672558 ProcessGroupNCCL.cpp:629] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=5111, OpType=_ALLGATHER_BASE, NumelIn=65553408, NumelOut=262213632, Timeout(ms)=600000) ran for 600009 milliseconds before timing out.
```

**Expected behavior**
The end-to-end jobs pass on the `main` branch

**Comment by ktdreyer** [comment]
(apologies, I had linked to the wrong job, and I've edited it to the [correct job](https://github.com/instructlab/instructlab/actions/runs/14711738459/job/41285794237) now.)

**Comment by ktdreyer** [comment]
@cdoern is testing a fix at https://github.com/instructlab/training/pull/507

**Comment by booxter** [comment]
Trying to collect some info here: https://github.com/instructlab/instructlab/pull/3323

**Comment by cdoern** [comment]
final fix here turned out to be the following: 

our runners were running out of storage on the third phased training test given that they were only set up with 800gb. This error did not manifest in the best way since it came from the GH runner itself not our code -- so it looked like an optimizer issue. Bumping the storage up solved the issue

**Comment by ktdreyer** [comment]
Thanks, and to add some more information:

@courtneypacheco added that disk space to the GH Actions runners by making a change in the AWS web console.
